openapi: 3.0.0
info:
  title: Physical AI Book RAG API
  version: 1.0.0
  description: Backend API for the RAG chatbot embedded in the Docusaurus book.
servers:
  - url: http://localhost:8000
    description: Local Development
paths:
  /api/v1/chat:
    post:
      summary: Send a query to the RAG chatbot
      operationId: chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  example: "How does a humanoid robot maintain balance?"
                history:
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        enum: [user, assistant]
                      content:
                        type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The generated answer based on the book.
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                        text:
                          type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /api/v1/feedback:
    post:
      summary: Submit feedback on a chat response
      operationId: feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message_id:
                  type: string
                rating:
                  type: string
                  enum: [positive, negative]
      responses:
        '200':
          description: Feedback recorded
