import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  modulesSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro-pages',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-01-ros2',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-02-digital-twin',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-03-isaac-brain',
        },
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: VLA',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-04-vla',
        },
      ],
      collapsed: false,
    },
    'references',
  ],
};

export default sidebars;
